version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
